npmScopes:
  axe-devtools:
      npmRegistries: 'https://agora.dequecloud.com/artifactory/api/npm/dequelabs/':
      npmAuthIdent: bW9raHRhcmFrbGVAZ21haWwuY29tOkFLQ3BCc2VYR2ZzQk04eXhyWjNBNlcyVHlDcENrRk1IMTk5M3ZLdmJobkJYY3NMcDNDbVB6b3V1VkdRWXZyRGI2aXBKNmhXMUw=
      npmRegistryServer: 'https://agora.dequecloud.com/artifactory/api/npm/dequelabs/'
      npmAlwaysAuth: true